import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/main.css";

const Nephilm = localFont({
  src: [
    {
      path: './styles/vendor/font/Nephilm.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './styles/vendor/font/Nephilm Italic.otf',
      weight: '400',
      style: 'italic',
    }
  ],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Nephilm.className}>{children}</body>
    </html>
  );
}
